const personData = {
  firstName: [
    "Serhey",
    "Serhi",
    "Serhii",
    "Serhij",
    "Serhiy",
    "Serhy",
    "Serhyi",
    "Serhyj",

    "Sergey",
    "Sergi",
    "Sergii",
    "Sergij",
    "Sergiy",
    "Sergy",
    "Sergyi",
    "Sergyj",
  ],
  lastName: [
    "Balinskia",
    "Balinskib",
    "Balinskic",
    "Balinskid",
    "Balinskie",
    "Balinskif",
    "Balinskig",
    "Balinskih",
    "Balinskii",
    "Balinskij",
    "Balinskik",
    "Balinskil",
    "Balinskim",
    "Balinskin",
    "Balinskio",
    "Balinskip",
    "Balinskiq",
    "Balinskir",
    "Balinskis",
    "Balinskit",
    "Balinskiu",
    "Balinskiv",
    "Balinskiw",
    "Balinskix",
    "Balinskiy",
    "Balinskiz",

    "Baljnskia",
    "Baljnskib",
    "Baljnskic",
    "Baljnskid",
    "Baljnskie",
    "Baljnskif",
    "Baljnskig",
    "Baljnskih",
    "Baljnskii",
    "Baljnskij",
    "Baljnskik",
    "Baljnskil",
    "Baljnskim",
    "Baljnskin",
    "Baljnskio",
    "Baljnskip",
    "Baljnskiq",
    "Baljnskir",
    "Baljnskis",
    "Baljnskit",
    "Baljnskiu",
    "Baljnskiv",
    "Baljnskiw",
    "Baljnskix",
    "Baljnskiy",
    "Baljnskiz",

    "Balinskja",
    "Balinskjb",
    "Balinskjc",
    "Balinskjd",
    "Balinskje",
    "Balinskjf",
    "Balinskjg",
    "Balinskjh",
    "Balinskji",
    "Balinskjj",
    "Balinskjk",
    "Balinskjl",
    "Balinskjm",
    "Balinskjn",
    "Balinskjo",
    "Balinskjp",
    "Balinskjq",
    "Balinskjr",
    "Balinskjs",
    "Balinskjt",
    "Balinskju",
    "Balinskjv",
    "Balinskjw",
    "Balinskjx",
    "Balinskjy",
    "Balinskjz",
  ],
  password: "20200831Pass!",
  country: "Ukraine",
  title: ["Full Stack Developer", "Senior Full Stack Developer"],
  companyData: {
    role: "Senior Full Stack Developer",
    name: "RentBarker",
    city: "Kyiv",
    startMonth: "January",
    startYear: "2018",
    endMonth: "November",
    endYear: "2022",
    description: `-  Developed full-stack web applications which processed, analyzed, and rendered data visually
    -  Liaised with back end developers, front end developers, quality assurance testers, and CTO as needed
    -  Managed time-sensitive updates, including content changes and database upgrades
    -  Planned, wrote, and debugged web applications and software with complete accuracy
    -  Spearheaded transition from LAMP stack to MERN stack, reducing latency by 40% and increasing database admin effectiveness by 20%
    `,
  },
  educationData: {
    universityName: "Sevastopol National Technical University",
    degree: "Bachelor of Computer Science",
    sector: "InfoTech",
    startYear: "2010",
    endYear: "2014",
    description: "",
  },
  englishLvl: "Fluent",
  skills: [
    "Javascript",
    "Typescript",
    "React",
    "Next.js",
    "Gatsby",
    "Vue.js",
    "Nuxt.js",
    "Node",
    "ExpressJS",
    "PHP",
    "Laravel",
    "Tailwind CSS",
    "MUI",
    "GraphQL",
  ],
  summary: `I am a full stack developer with rich experience in building websites for small and medium-sized businesses.
  So confident with my knowledge and expertise which I achieved in the past working on many projects based on different industries.
  I have developed several web applications from scratch, and at the same time fixed and updated existing projects too with my outstanding debugging skills.
  Now looking for a new challenge with innovative ideas and top-notch coding skills.
  `,
  street: "Boychuka Mykhayla street, 39",
  city: "kyiv",
  phone: "123456789",
  hourlyRate: "3",
  avatarUrl: ["C:/Avatars/1.png"],
};

module.exports = {
  personData,
};
